name_kwap = input("Enter your name: ")
age_kwap = input("Enter your age: ")
course_kwap = input("Enter your course: ")
university_kwap = input("Enter your university: ")
print("\n----- STUDENT PROFILE -----")
print("Name:", name_kwap)
print("Age:", age_kwap)
print("Course:", course_kwap)
print("University:", university_kwap)
